import React, { useState } from "react";
import FeedbackButtons from "../FeedbackButtons";

/**
 * InterviewPrepPanel renders candidate-specific interview questions.
 * Features type filter pills, expandable question detail cards, model answers with a copy action,
 * and interviewer focal points checklists.
 */
export default function InterviewPrepPanel({ data }) {
  const [activeFilter, setActiveFilter] = useState("All");
  const [expandedIdx, setExpandedIdx] = useState(null);
  const [copiedIdx, setCopiedIdx] = useState(null);

  if (!data || !data.questions || data.questions.length === 0) {
    return (
      <div className="bg-[#432818] border border-[#99582a] rounded-2xl p-8 text-center animate-fadeIn text-[#ffe6a7]">
        <div className="w-12 h-12 rounded-xl bg-[#6f1d1b] border border-[#99582a] flex items-center justify-center text-[#bb9457] mx-auto mb-4 shadow-md">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z"
            />
          </svg>
        </div>
        <h4 className="text-base font-bold text-[#ffe6a7] mb-1">
          Interview Prep Unavailable
        </h4>
        <p className="text-[#99582a] text-xs max-w-xs mx-auto leading-relaxed">
          Interview questions could not be generated — try re-analyzing your resume.
        </p>
      </div>
    );
  }

  const filters = ["All", "Technical", "Project", "Behavioral", "Situational", "Curveball"];
  
  const filteredQuestions = data.questions.filter((q) => {
    if (activeFilter === "All") return true;
    return q.type?.toLowerCase() === activeFilter.toLowerCase();
  });

  const handleCopy = (e, index, text) => {
    e.stopPropagation();
    navigator.clipboard.writeText(text);
    setCopiedIdx(index);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const toggleExpand = (index) => {
    setExpandedIdx(expandedIdx === index ? null : index);
  };

  return (
    <div className="bg-[#432818] border border-[#99582a] rounded-[16px] p-6 shadow-2xl space-y-6 animate-fadeIn text-[#ffe6a7]">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h3 className="text-xl font-bold text-[#ffe6a7] mb-1">Interview Prep</h3>
          <p className="text-[#bb9457] text-sm font-medium">
            Tailored questions generated by AI based on your background and projects.
          </p>
        </div>
      </div>

      {/* Filter Pills */}
      <div className="flex flex-wrap gap-2 pb-2">
        {filters.map((f) => {
          const isSelected = activeFilter === f;
          return (
            <button
              key={f}
              onClick={() => {
                setActiveFilter(f);
                setExpandedIdx(null);
              }}
              className={`px-4 py-1.5 rounded-full text-xs font-bold transition-all duration-200 ${
                isSelected
                  ? "bg-[#bb9457] text-[#432818]"
                  : "bg-[#6f1d1b]/40 text-[#ffe6a7] border border-[#99582a]/30 hover:border-[#bb9457]/50"
              }`}
            >
              {f}
            </button>
          );
        })}
      </div>

      {/* Questions list */}
      <div className="space-y-4">
        {filteredQuestions.length > 0 ? (
          filteredQuestions.map((q, idx) => {
            const isExpanded = expandedIdx === idx;
            
            let diffColor = "bg-[#6f1d1b] text-[#ffe6a7] border border-[#99582a]/30";
            if (q.difficulty?.toLowerCase() === "easy") {
              diffColor = "bg-[#1a7a4a]/20 text-[#1a7a4a] border border-[#1a7a4a]/30";
            } else if (q.difficulty?.toLowerCase() === "medium") {
              diffColor = "bg-[#bb9457]/20 text-[#bb9457] border border-[#bb9457]/30";
            } else if (q.difficulty?.toLowerCase() === "hard") {
              diffColor = "bg-[#c0392b]/20 text-[#c0392b] border border-[#c0392b]/30";
            }

            return (
              <div
                key={idx}
                onClick={() => toggleExpand(idx)}
                className="bg-[#432818] border border-[#99582a] hover:border-[#bb9457] rounded-xl p-5 transition-all duration-200 cursor-pointer shadow-sm"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="space-y-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="px-2.5 py-0.5 rounded-[50px] text-[10px] font-bold bg-[#6f1d1b] text-[#bb9457] border border-[#99582a]/30 uppercase tracking-wider">
                        {q.type}
                      </span>
                      <span className={`px-2.5 py-0.5 rounded-[50px] text-[10px] font-bold uppercase tracking-wider ${diffColor}`}>
                        {q.difficulty}
                      </span>
                    </div>
                    <h4 className="text-base font-extrabold text-[#ffe6a7] leading-relaxed">
                      {q.question}
                    </h4>
                  </div>
                  <span className="text-[#bb9457] text-lg font-bold select-none pt-1">
                    {isExpanded ? "▲" : "▼"}
                  </span>
                </div>

                {isExpanded && (
                  <div
                    className="mt-5 pt-5 border-t border-[#99582a]/30 space-y-5 animate-fadeIn"
                    onClick={(e) => e.stopPropagation()}
                  >
                    {/* Model Answer */}
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <h5 className="text-[11px] font-bold text-[#bb9457] uppercase tracking-wider">
                          Tailored Model Answer (First Person)
                        </h5>
                        <button
                          onClick={(e) => handleCopy(e, idx, q.model_answer)}
                          className="text-xs text-[#bb9457] hover:text-[#ffe6a7] font-semibold flex items-center gap-1 transition"
                        >
                          {copiedIdx === idx ? "Copied! ✓" : "Copy Answer"}
                        </button>
                      </div>
                      <div className="bg-[#6f1d1b] border-l-4 border-[#bb9457] rounded-r-xl p-4 text-[#ffe6a7] text-sm leading-relaxed italic whitespace-pre-line">
                        "{q.model_answer}"
                      </div>
                    </div>

                    {/* focal points */}
                    {q.key_points && q.key_points.length > 0 && (
                      <div className="space-y-2">
                        <h5 className="text-[11px] font-bold text-[#bb9457] uppercase tracking-wider">
                          What the Interviewer is Evaluating
                        </h5>
                        <ul className="space-y-2">
                          {q.key_points.map((pt, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-[#ffe6a7]/90">
                              <span className="text-[#bb9457] mt-0.5 flex-shrink-0">•</span>
                              <span>{pt}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Feedback — was this question/answer relevant to the candidate's background? */}
                    <div className="flex items-center gap-2 pt-1">
                      <span className="text-[#99582a] text-[11px] font-semibold">Was this relevant?</span>
                      <FeedbackButtons
                        feature="interview_question"
                        itemId={`question_${idx}`}
                        context={{ question: q.question, type: q.type }}
                      />
                    </div>
                  </div>
                )}
              </div>
            );
          })
        ) : (
          <div className="text-center py-8 text-[#99582a] text-sm italic">
            No questions found for the selected category.
          </div>
        )}
      </div>
    </div>
  );
}